// app/resources/js/Components/Navigation/Sidebar.vue
<template>
  <aside class="flex w-64 shrink-0 flex-col bg-[#0F172A] text-white border-r border-slate-800 h-screen sticky top-0">
    <!-- Logo -->
    <div class="flex items-center gap-3 p-6">
      <div class="flex h-8 w-8 items-center justify-center rounded-lg bg-gradient-to-br from-blue-600 to-violet-600 shadow-lg shadow-blue-500/20">
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="h-5 w-5 text-white">
          <path fill-rule="evenodd" d="M12.516 2.17a.75.75 0 00-1.032 0 11.209 11.209 0 01-7.877 3.08.75.75 0 00-.722.515A12.74 12.74 0 002.25 9.75c0 5.942 4.064 10.933 9.563 12.348a.749.749 0 00.374 0c5.499-1.415 9.563-6.406 9.563-12.348 0-1.39-.223-2.73-.635-3.985a.75.75 0 00-.722-.516 11.209 11.209 0 01-7.877-3.08z" clip-rule="evenodd" />
        </svg>
      </div>
      <div class="flex flex-col">
        <span class="text-base font-bold tracking-tight leading-none">AEGIS MAILING</span>
        <span class="mt-1 text-[10px] font-medium uppercase tracking-widest text-slate-400">Premium B2B</span>
      </div>
    </div>

    <!-- Navigation -->
    <nav class="flex-1 overflow-y-auto px-4 py-4 custom-scrollbar">
      <p class="px-3 py-2 text-xs font-semibold uppercase tracking-wider text-slate-500">Menu Principal</p>
      <ul class="space-y-1">
        <SidebarItem
          v-for="item in navItems"
          :key="item.id"
          :item="item"
          :active="current === item.id"
        />
      </ul>

      <p class="mt-6 px-3 py-2 text-xs font-semibold uppercase tracking-wider text-slate-500">Configuration</p>
      <ul class="space-y-1">
        <SidebarItem
          v-for="item in bottomItems"
          :key="item.id"
          :item="item"
          :active="current === item.id"
        />
      </ul>
    </nav>

    <!-- User card -->
    <div class="border-t border-slate-800 bg-slate-900/50 p-4">
      <div class="flex items-center gap-3 rounded-xl border border-slate-700/50 bg-slate-800/50 p-2">
        <div class="flex h-10 w-10 shrink-0 items-center justify-center rounded-full border-2 border-slate-600 bg-slate-700 text-sm font-bold text-white">
          {{ initials }}
        </div>
        <div class="min-w-0 flex-1">
          <p class="truncate text-sm font-bold text-white">{{ userName }}</p>
          <p class="text-[10px] font-medium text-slate-400">Administrateur</p>
        </div>
      </div>
    </div>
  </aside>
</template>

<script setup>
import { computed } from 'vue';
import { usePage } from '@inertiajs/vue3';
import SidebarItem from './SidebarItem.vue';

defineProps({
  current: { type: String, default: '' },
});

const page = usePage();
const userName = computed(() => page.props.auth?.user?.name || 'Utilisateur');
const initials = computed(() => {
  const name = userName.value;
  return name.split(' ').map(n => n[0]).join('').substring(0, 2).toUpperCase();
});

const navItems = [
  { id: 'dashboard', label: 'Dashboard', href: '/dashboard', icon: 'dashboard' },
  { id: 'contacts', label: 'Contacts', href: '/contacts', icon: 'contacts' },
  { id: 'organizations', label: 'Organisations', href: '/organizations', icon: 'organizations' },
  { id: 'mails', label: 'Mails', href: '/mails', icon: 'mail' },
  { id: 'drafts', label: 'Brouillons', href: '/drafts', icon: 'draft' },
  { id: 'templates', label: 'Modèles', href: '/templates', icon: 'template' },
  { id: 'campaigns', label: 'Campagnes', href: '/campaigns', icon: 'campaign' },
  { id: 'activity', label: 'Activité', href: '/activity', icon: 'activity' },
];

const bottomItems = [
  { id: 'settings', label: 'Réglages', href: '/settings', icon: 'settings' },
  { id: 'users', label: 'Utilisateurs', href: '/users', icon: 'users' },
];
</script>

// stitch/v1/components/Sidebar.tsx
'use client';

import Link from 'next/link';
import Image from 'next/image';
import { usePathname } from 'next/navigation';
import {
  LayoutDashboard,
  Send,
  Users,
  Building2,
  Inbox,
  FileText,
  Activity,
  Settings,
  UserCircle,
  Shield,
  LogOut,
  Mail,
  FileEdit
} from 'lucide-react';

const navigation = [
  { name: 'Tableau de bord', href: '/', icon: LayoutDashboard },
  { name: 'Campagnes', href: '/campaigns', icon: Send },
  { name: 'Contacts', href: '/contacts', icon: Users },
  { name: 'Organisations', href: '/organisations', icon: Building2 },
  { name: 'Boîte de réception', href: '/inbox', icon: Inbox },
  { name: 'Brouillons', href: '/drafts', icon: FileEdit },
  { name: 'Modèles', href: '/templates', icon: FileText },
  { name: 'Flux d\'activité', href: '/activity', icon: Activity },
];

const bottomNavigation = [
  { name: 'Paramètres', href: '/settings', icon: Settings },
  { name: 'Utilisateurs', href: '/users', icon: UserCircle },
];

export function Sidebar() {
  const pathname = usePathname();

  return (
    <aside className="w-64 bg-[#0F172A] text-white flex flex-col flex-shrink-0 border-r border-slate-800 h-screen sticky top-0">
      <div className="p-6 flex items-center gap-3">
        <div className="w-8 h-8 bg-gradient-to-br from-blue-600 to-violet-600 rounded-lg flex items-center justify-center shadow-lg shadow-blue-500/20">
          <Shield className="w-5 h-5 text-white" />
        </div>
        <div className="flex flex-col">
          <span className="font-bold text-base tracking-tight leading-none">AEGIS MAILING</span>
          <span className="text-[10px] text-slate-400 font-medium uppercase tracking-widest mt-1">Premium B2B</span>
        </div>
      </div>

      <nav className="flex-1 px-4 py-4 space-y-1 overflow-y-auto custom-scrollbar">
        <div className="text-xs font-semibold text-slate-500 uppercase px-3 py-2 tracking-wider">Menu Principal</div>
        {navigation.map((item) => {
          const isActive = pathname === item.href;
          return (
            <Link
              key={item.name}
              href={item.href}
              className={`flex items-center gap-3 px-3 py-2.5 rounded-xl transition-all ${
                isActive
                  ? 'bg-blue-600/10 text-blue-500 border border-blue-500/20 font-bold'
                  : 'text-slate-400 hover:text-white hover:bg-slate-800/50 font-medium'
              }`}
            >
              <item.icon className="w-5 h-5" />
              <span className="text-sm">{item.name}</span>
            </Link>
          );
        })}

        <div className="pt-6 text-xs font-semibold text-slate-500 uppercase px-3 py-2 tracking-wider">Configuration</div>
        {bottomNavigation.map((item) => {
          const isActive = pathname === item.href;
          return (
            <Link
              key={item.name}
              href={item.href}
              className={`flex items-center gap-3 px-3 py-2.5 rounded-xl transition-all ${
                isActive
                  ? 'bg-blue-600/10 text-blue-500 border border-blue-500/20 font-bold'
                  : 'text-slate-400 hover:text-white hover:bg-slate-800/50 font-medium'
              }`}
            >
              <item.icon className="w-5 h-5" />
              <span className="text-sm">{item.name}</span>
            </Link>
          );
        })}
      </nav>

      <div className="p-4 border-t border-slate-800 bg-slate-900/50">
        <div className="flex items-center gap-3 p-2 rounded-xl bg-slate-800/50 border border-slate-700/50">
          <div className="w-10 h-10 rounded-full bg-slate-700 overflow-hidden border-2 border-slate-600 shrink-0 relative">
            <Image
              src="https://api.dicebear.com/7.x/avataaars/svg?seed=Felix"
              alt="Avatar Utilisateur"
              fill
              referrerPolicy="no-referrer"
              className="object-cover"
            />
          </div>
          <div className="flex-1 min-w-0">
            <p className="text-sm font-bold truncate text-white">Jean Dupont</p>
            <p className="text-[10px] text-slate-400 truncate uppercase tracking-wider">Admin Compte</p>
          </div>
          <button className="text-slate-500 hover:text-white transition-colors p-1">
            <LogOut className="w-4 h-4" />
          </button>
        </div>
      </div>
    </aside>
  );
}
